apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: boltapi-repo
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/Pavanpatil214/fluxcd
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: boltapi-helmrelease
  namespace: default
spec:
  timeout: 10m
  interval: 2m0s
  reconcileStrategy: Revision
  chart:
    spec:
      chart: ./helm-chart
      sourceRef:
        kind: GitRepository
        name: boltapi-repo
  values:
    image:
      repository: "mcr.microsoft.com/azuredocs/aks-helloworld"
      tag: "v1"
