apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: boltapi-repo
  namespace: default
spec:
  interval: 3m0s
  url: https://github.com/Pavanpatil214/fluxcd
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: boltapi-helmrelease
  namespace: default
spec:
  timeout: 10m
  interval: 2m
  chart:
    spec:
      chart: ./helm-chart
      sourceRef:
        kind: GitRepository
        name: boltapi-repo
      interval: 1m
      valuesFiles:
        - ./dev-values.yaml