apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: boltapi-repo
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/Pavanpatil214/fluxcd
  ref:
    branch: main

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: bolt-helm-chart
  namespace: default
spec:
  interval: 2m0s
  chart: ./helm-chart
  sourceRef:
    kind: GitRepository
    name: boltapi-repo


---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: boltapi-helmrelease
  namespace: default
spec:
  timeout: 10m
  interval: 2m0s
  chart:
    spec:
      chart: ./helm-chart
      sourceRef:
        kind: GitRepository
        name: boltapi-repo
      interval: 1m0s
