name: Chart Update

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest commit ID
        id: get_commit_id
        run: |
          COMMIT_ID=$(date +"%Y%m%d_%H%M%S")
          echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Increment Helm chart version
        run: |
          CHART_FILE="./helm-chart/Chart.yaml"
          VERSION=$(grep '^version:' $CHART_FILE | awk '{print $2}')
          IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          if [ "$PATCH" -lt 9 ]; then
            PATCH=$((PATCH + 1))
          else
            PATCH=0
            if [ "$MINOR" -lt 9 ]; then
              MINOR=$((MINOR + 1))
            else
              MINOR=0
              MAJOR=$((MAJOR + 1))
            fi
          fi
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          sed -i "s/^version:.*/version: $NEW_VERSION/" $CHART_FILE
          echo "Updated version from $VERSION to $NEW_VERSION"

      - name: Update Helm chart values
        run: |
          sed -i 's/tags:.*/tags: "${{ env.COMMIT_ID }}"/' ./helm-chart/values.yaml

      - name: Commit changes to values.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add ./helm-chart/Chart.yaml ./helm-chart/values.yaml
          git commit -m "Update Helm chart Tag values with commit ID" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${{ env.BRANCH_NAME }}
