name: Update Tag Branch Create

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest commit ID
        id: get_commit_id
        run: |
          COMMIT_ID=$(date +"%Y%m%d_%H%M%S")
          echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV

      - name: Create temporary branch for Helm chart update
        run: |
          BRANCH_NAME="update-helm-chart-${{ env.COMMIT_ID }}"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Update Helm chart values
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sed -i "s/tag:.*/tag: ${{ env.COMMIT_ID }}/" ./values.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./values.yaml
          git commit -m "Update Helm chart with new image tag ${{ env.COMMIT_ID }}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${{ env.BRANCH_NAME }}

      - name: Wait for branch to be available
        run: sleep 3

      - name: Fetch remote branches
        run: git fetch origin

      - name: Verify branch exists
        run: |
          git branch -r | grep "origin/${{ env.BRANCH_NAME }}"

      - name: Verify changes in branch
        run: |
          git diff origin/main...${{ env.BRANCH_NAME }}

      - name: Create Pull Request for Helm chart update
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Update Helm chart with new image tag'
          body: 'Automated PR to update Helm chart with new image tag ${{ env.COMMIT_ID }}'
          base: main
          branch: ${{ env.BRANCH_NAME }}
          commit-message: 'Update Helm chart values'
