name: Update Tag Branch Create

on:
  workflow_dispatch:

jobs:
  update-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest commit ID
        id: get_commit_id
        run: |
          COMMIT_ID=$(date +"%Y%m%d_%H%M%S")
          echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV

      - name: Create temporary branch for Helm chart update
        run: |
          BRANCH_NAME="update-helm-chart-${{ env.COMMIT_ID }}"
          git checkout -b $BRANCH_NAME

      - name: Update Helm chart values
        run: |
          sed -i 's/tag:.*/tag: ${{ env.COMMIT_ID }}/' ./values.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./values.yaml
          git commit -m "Update Helm chart with new image tag ${{ env.COMMIT_ID }}"
          git push origin ${{ env.BRANCH_NAME }}

      - name: Create Pull Request for Helm chart update
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Update Helm chart with new image tag ${{ env.COMMIT_ID }}'
          body: 'Automated PR to update Helm chart with new image tag ${{ env.COMMIT_ID }}'
          base: main
          head: update-helm-chart-${{ env.COMMIT_ID }}
          files: |
            ./values.yaml
          commit-message: 'Update Helm chart values'
